#!/usr/bin/env python3
"""Export a deterministic inventory of the production PloidyPatch CLI."""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path

from ploidypatch import __version__
from ploidypatch.cli import build_parser


SCHEMA_VERSION = "ploidypatch.cli_command_inventory.v1"


def _command_nodes(
    parser: argparse.ArgumentParser,
    prefix: tuple[str, ...] = (),
) -> list[tuple[tuple[str, ...], bool]]:
    nodes: list[tuple[tuple[str, ...], bool]] = []
    for action in parser._actions:
        if not isinstance(action, argparse._SubParsersAction):
            continue
        for name in sorted(action.choices):
            child = action.choices[name]
            path = (*prefix, name)
            has_children = any(
                isinstance(child_action, argparse._SubParsersAction)
                for child_action in child._actions
            )
            nodes.append((path, has_children))
            nodes.extend(_command_nodes(child, path))
    return nodes


def build_inventory() -> dict[str, object]:
    nodes = _command_nodes(build_parser())
    leaf_paths = sorted(" ".join(path) for path, has_children in nodes if not has_children)
    family_counts = Counter(path.split(" ", 1)[0] for path in leaf_paths)
    top_level = sorted(path[0] for path, _ in nodes if len(path) == 1)
    return {
        "schema_version": SCHEMA_VERSION,
        "package_version": __version__,
        "parser": "ploidypatch.cli.build_parser",
        "top_level_families": top_level,
        "leaf_command_count": len(leaf_paths),
        "leaf_commands_by_family": dict(sorted(family_counts.items())),
        "leaf_commands": leaf_paths,
    }


def inventory_bytes() -> bytes:
    text = json.dumps(build_inventory(), indent=2, sort_keys=True) + "\n"
    return text.encode("utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare generated bytes with an existing inventory",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    expected = inventory_bytes()
    if args.check:
        if not args.output.is_file() or args.output.is_symlink():
            raise FileNotFoundError(f"missing regular inventory: {args.output}")
        actual = args.output.read_bytes()
        if actual != expected:
            raise ValueError(f"CLI inventory differs: {args.output}")
        print(f"CLI inventory is current: {args.output}")
        return 0
    if args.output.exists():
        raise FileExistsError(f"refusing to overwrite CLI inventory: {args.output}")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("xb") as handle:
        handle.write(expected)
    print(f"wrote CLI inventory: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
